general:
  save_output: true
model:
  onnx_path: /home/shauntan/benchmark_selection_experiment/models/mnist/convMedGRELU__Point.onnx
data:
  dataset: MNIST_ERAN_UN
  start: 0
  end: 200
specification:
  epsilon: 0.1
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 300
  branching:
    reduceop: max
