general:
  save_output: true
model:
  onnx_path: /home/shauntan/benchmark_selection_experiment/models/cifar10/convMedGRELU__PGDK_w_0.0078.onnx
data:
  dataset: CIFAR_ERAN
  start: 0
  end: 200
specification:
  epsilon: 0.006
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 300
  branching:
    reduceop: max
